# Generated by Django 4.2.5 on 2023-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recepie_image',
            field=models.ImageField(default=None, null=True, upload_to='recepie/'),
        ),
    ]
